"""XGBoost priority recommendation for accessibility reports.

The authority portal never receives a priority from the CSV import - priority
is a *recommendation* produced here and then confirmed (or overridden) by a
human reviewer.

Model lifecycle
---------------
1. On first use the module trains an :class:`xgboost.XGBClassifier` on a
   deterministic, labelled corpus generated by :func:`build_training_set`
   (rule-derived labels plus controlled label noise, so the tree learns the
   interactions rather than memorising a single rule).
2. The booster is cached in-process and persisted to ``ML_MODEL_DIR`` so warm
   serverless containers reuse it.
3. If XGBoost cannot be imported, scikit-learn's gradient boosting is used;
   if neither is available the deterministic rule engine answers directly.
   Every response reports which backend produced it.
"""

from __future__ import annotations

import datetime as dt
import logging
import os
import random
import threading

from backend.core.config import settings
from backend.core.constants import ISSUE_TYPES, PRIORITIES, REPORT_SOURCES, SEVERITIES
from backend.ml import features as feat

logger = logging.getLogger("routesathi.ml")

_lock = threading.Lock()
_model = None
_backend = "rules"
_MODEL_FILE = "priority_xgb.json"
_TRAINING_ROWS = 4000
_SEED = 20260831


# ---------------------------------------------------------------------------
# Deterministic rule engine (label source + always-available fallback)
# ---------------------------------------------------------------------------
def rule_score(
    *,
    issue_type: str,
    severity: str,
    source: str | None,
    description: str | None,
    has_image: bool,
    timestamp: dt.datetime | None,
    validation_status: str | None = None,
    now: dt.datetime | None = None,
) -> float:
    """Return a 0-1 urgency score."""
    impact = feat.ISSUE_IMPACT.get(issue_type, 0.35)
    severity_weight = {"Low": 0.15, "Medium": 0.45, "High": 0.85}.get(severity, 0.3)
    trust = feat.SOURCE_TRUST.get(source or "Other", 0.4)
    age = feat._age_days(timestamp, now)

    score = 0.40 * impact + 0.34 * severity_weight + 0.10 * trust
    score += 0.08 * min(age / 21.0, 1.0)          # ageing reports drift upward
    score += 0.05 if has_image else 0.0            # evidence increases confidence
    score += 0.03 if validation_status == "Valid" else 0.0
    if description and len(description) > 120:
        score += 0.02
    return max(0.0, min(1.0, score))


def score_to_priority(score: float) -> str:
    if score >= 0.78:
        return "Critical"
    if score >= 0.62:
        return "High"
    if score >= 0.42:
        return "Medium"
    return "Low"


# ---------------------------------------------------------------------------
# Training corpus
# ---------------------------------------------------------------------------
def build_training_set(rows: int = _TRAINING_ROWS, seed: int = _SEED):
    """Generate a reproducible labelled dataset of report feature vectors."""
    rng = random.Random(seed)
    now = dt.datetime(2026, 8, 31, tzinfo=dt.timezone.utc)
    X: list[list[float]] = []
    y: list[int] = []

    for _ in range(rows):
        issue_type = rng.choice(ISSUE_TYPES)
        severity = rng.choices(SEVERITIES, weights=[3, 4, 3])[0]
        source = rng.choice(REPORT_SOURCES)
        has_image = rng.random() < 0.62
        description = "x" * rng.randint(20, 400)
        age_days = rng.random() * 45
        timestamp = now - dt.timedelta(days=age_days, hours=rng.randint(0, 23))
        validation_status = rng.choices(
            ["Needs Review", "Valid", "Invalid"], weights=[5, 4, 1]
        )[0]

        score = rule_score(
            issue_type=issue_type,
            severity=severity,
            source=source,
            description=description,
            has_image=has_image,
            timestamp=timestamp,
            validation_status=validation_status,
            now=now,
        )
        # Controlled noise so the classifier learns a smooth boundary rather
        # than an exact reproduction of the thresholds.
        score += rng.gauss(0.0, 0.05)
        label = PRIORITIES.index(score_to_priority(max(0.0, min(1.0, score))))

        X.append(
            feat.extract(
                issue_type=issue_type,
                severity=severity,
                source=source,
                description=description,
                has_image=has_image,
                timestamp=timestamp,
                validation_status=validation_status,
                now=now,
            )
        )
        y.append(label)

    return X, y


# ---------------------------------------------------------------------------
# Model loading / training
# ---------------------------------------------------------------------------
def _model_path() -> str:
    return os.path.join(settings.ml_model_dir, _MODEL_FILE)


def _train_xgboost():
    import numpy as np
    from xgboost import XGBClassifier

    X, y = build_training_set()
    model = XGBClassifier(
        n_estimators=180,
        max_depth=4,
        learning_rate=0.16,
        subsample=0.9,
        colsample_bytree=0.9,
        objective="multi:softprob",
        num_class=len(PRIORITIES),
        eval_metric="mlogloss",
        tree_method="hist",
        random_state=_SEED,
        n_jobs=1,
    )
    model.fit(np.asarray(X, dtype="float32"), np.asarray(y))
    try:
        os.makedirs(settings.ml_model_dir, exist_ok=True)
        model.save_model(_model_path())
    except OSError as exc:  # pragma: no cover - read-only fs on some runtimes
        logger.warning("Could not persist the priority model: %s", exc)
    return model


def _load_xgboost():
    from xgboost import XGBClassifier

    path = _model_path()
    if not os.path.isfile(path):
        return None
    model = XGBClassifier()
    model.load_model(path)
    return model


def _train_sklearn():
    import numpy as np
    from sklearn.ensemble import GradientBoostingClassifier

    X, y = build_training_set(rows=1500)
    model = GradientBoostingClassifier(random_state=_SEED)
    model.fit(np.asarray(X, dtype="float64"), np.asarray(y))
    return model


def get_model():
    """Return ``(model, backend_name)``; ``model`` is ``None`` for the rule engine."""
    global _model, _backend
    if _model is not None or _backend == "rules-only":
        return _model, _backend
    if not settings.ml_enabled:
        _backend = "rules"
        return None, _backend

    with _lock:
        if _model is not None:
            return _model, _backend
        try:
            model = _load_xgboost() or _train_xgboost()
            _model, _backend = model, "xgboost"
            return _model, _backend
        except Exception as exc:
            logger.warning("XGBoost unavailable (%s); trying scikit-learn", exc)
        try:
            _model, _backend = _train_sklearn(), "sklearn-gbm"
            return _model, _backend
        except Exception as exc:
            logger.warning("scikit-learn unavailable (%s); using rule engine", exc)
            _backend = "rules-only"
            return None, _backend


def backend_name() -> str:
    _, backend = get_model()
    return backend


# ---------------------------------------------------------------------------
# Inference
# ---------------------------------------------------------------------------
def predict(
    *,
    issue_type: str,
    severity: str,
    source: str | None = None,
    description: str | None = None,
    has_image: bool = False,
    timestamp: dt.datetime | None = None,
    validation_status: str | None = None,
) -> dict:
    """Predict the priority of a single report.

    Returns ``{priority, confidence, model, probabilities, rationale}``.
    """
    kwargs = dict(
        issue_type=issue_type,
        severity=severity,
        source=source,
        description=description,
        has_image=has_image,
        timestamp=timestamp,
        validation_status=validation_status,
    )
    model, backend = get_model()
    rationale = feat.explain(
        issue_type=issue_type,
        severity=severity,
        source=source,
        has_image=has_image,
        timestamp=timestamp,
        validation_status=validation_status,
    )

    if model is not None:
        try:
            import numpy as np

            vector = np.asarray([feat.extract(**kwargs)], dtype="float32")
            probabilities = model.predict_proba(vector)[0]
            index = int(probabilities.argmax())
            return {
                "priority": PRIORITIES[index],
                "confidence": round(float(probabilities[index]), 4),
                "model": backend,
                "probabilities": {
                    name: round(float(probabilities[i]), 4)
                    for i, name in enumerate(PRIORITIES)
                },
                "rationale": rationale,
            }
        except Exception as exc:  # pragma: no cover
            logger.warning("Priority inference failed (%s); using rule engine", exc)

    score = rule_score(**kwargs)
    priority = score_to_priority(score)
    # Confidence for the rule engine = distance from the nearest band edge.
    edges = [0.0, 0.42, 0.62, 0.78, 1.0]
    lower = max(e for e in edges if e <= score)
    upper = min(e for e in edges if e > score) if score < 1.0 else 1.0
    width = max(upper - lower, 1e-6)
    confidence = round(0.55 + 0.4 * min((score - lower) / width, 1.0), 4)
    return {
        "priority": priority,
        "confidence": confidence,
        "model": "rules",
        "probabilities": {
            name: (1.0 if name == priority else 0.0) for name in PRIORITIES
        },
        "rationale": rationale,
    }
